---
# tasks file for httpd
- name: install apache server   # name of the play
  yum:
    name: httpd
    state: latest
    update_cache: yes
- name: Reboot machine and send a message
  ansible.builtin.reboot:
    msg: "Rebooting machine in 5 seconds"
- name: start and enable autostart of apache server
  systemd:
    name: httpd
    state: started
    enabled: yes

      #    - name: Install apache httpd
      # ansible.builtin.apt:
      # name: apache2
      #state: present
      #update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'

